'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { IonPhaserCe as IonPhaserCeElement, defineCustomElement as defineIonPhaserCe } from "@ion-phaser-ce/core/dist/components/ion-phaser-ce.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type IonPhaserCeEvents = NonNullable<unknown>;

export const IonPhaserCe: StencilReactComponent<IonPhaserCeElement, IonPhaserCeEvents> = /*@__PURE__*/ createComponent<IonPhaserCeElement, IonPhaserCeEvents>({
    tagName: 'ion-phaser-ce',
    elementClass: IonPhaserCeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as IonPhaserCeEvents,
    defineCustomElement: defineIonPhaserCe
});
