/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GameInstance } from "./components/models/game";
export { GameInstance } from "./components/models/game";
export namespace Components {
    interface IonPhaserCe {
        /**
          * Destroy the Phaser game instance
         */
        "destroy": () => Promise<void>;
        /**
          * Set the configuration of the game
         */
        "game"?: GameInstance;
        /**
          * Get the Phaser game instance
         */
        "getInstance": () => Promise<GameInstance["instance"]>;
        /**
          * Initialize the phaser game manually
          * @default true
         */
        "initialize"?: boolean;
    }
}
declare global {
    interface HTMLIonPhaserCeElement extends Components.IonPhaserCe, HTMLStencilElement {
    }
    var HTMLIonPhaserCeElement: {
        prototype: HTMLIonPhaserCeElement;
        new (): HTMLIonPhaserCeElement;
    };
    interface HTMLElementTagNameMap {
        "ion-phaser-ce": HTMLIonPhaserCeElement;
    }
}
declare namespace LocalJSX {
    interface IonPhaserCe {
        /**
          * Set the configuration of the game
         */
        "game"?: GameInstance;
        /**
          * Initialize the phaser game manually
          * @default true
         */
        "initialize"?: boolean;
    }

    interface IonPhaserCeAttributes {
        "initialize": boolean;
    }

    interface IntrinsicElements {
        "ion-phaser-ce": Omit<IonPhaserCe, keyof IonPhaserCeAttributes> & { [K in keyof IonPhaserCe & keyof IonPhaserCeAttributes]?: IonPhaserCe[K] } & { [K in keyof IonPhaserCe & keyof IonPhaserCeAttributes as `attr:${K}`]?: IonPhaserCeAttributes[K] } & { [K in keyof IonPhaserCe & keyof IonPhaserCeAttributes as `prop:${K}`]?: IonPhaserCe[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ion-phaser-ce": LocalJSX.IntrinsicElements["ion-phaser-ce"] & JSXBase.HTMLAttributes<HTMLIonPhaserCeElement>;
        }
    }
}
