/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  GameInstance,
} from './components/models';
import {
  Game,
} from 'phaser-ce';

export namespace Components {
  interface IonPhaserCe {
    /**
    * Destroy the Phaser game instance
    */
    'destroy': () => Promise<void>;
    /**
    * The configuration of the game
    */
    'game': GameInstance;
    /**
    * Get the Phaser game instance
    */
    'getInstance': () => Promise<Phaser.Game>;
    /**
    * To initialize the plugin manually
    */
    'initialize': boolean;
  }
}

declare global {


  interface HTMLIonPhaserCeElement extends Components.IonPhaserCe, HTMLStencilElement {}
  var HTMLIonPhaserCeElement: {
    prototype: HTMLIonPhaserCeElement;
    new (): HTMLIonPhaserCeElement;
  };
  interface HTMLElementTagNameMap {
    'ion-phaser-ce': HTMLIonPhaserCeElement;
  }
}

declare namespace LocalJSX {
  interface IonPhaserCe {
    /**
    * The configuration of the game
    */
    'game'?: GameInstance;
    /**
    * To initialize the plugin manually
    */
    'initialize'?: boolean;
  }

  interface IntrinsicElements {
    'ion-phaser-ce': IonPhaserCe;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ion-phaser-ce': LocalJSX.IonPhaserCe & JSXBase.HTMLAttributes<HTMLIonPhaserCeElement>;
    }
  }
}


